### ISSUE TITLE
[Bot]: vtuberplus is a good bot used vtubing.

### ISSUE THREAD

**Issue by Sanders47** [arrowgent/Twitchtv-Bots-List#12]
### BOT NAME

vtuberplus

### verify

Used by this app. (https://store.steampowered.com/app/1957330/VTuber_Plus/)

### Version

BOT

### What system are you seeing the bot on?

Botlist

### CODE

- [X] i am human

**Comment by arrowgent** [comment]
thank you,  the list is fairly automated from a website that tracks users which visit over 150 channels in less than 24 hours
i have updated "goodbot.txt" so it should get removed if it shows up again during automation

https://github.com/arrowgent/Twitchtv-Bots-List/commit/14148dd26d559b390bb5b65019f5151f7f837741
