### ISSUE TITLE
[Bot]: ElenaBerry

### ISSUE THREAD

**Issue by elenawinters** [arrowgent/Twitchtv-Bots-List#20]
### BOT NAME

elenaberry

### verify

I've appeared on the twitch insights bot list as well as this one.

Was doing tests and I had it connect to hundreds of channels to gather chat data to feed to my parser so I could perfect it.

I stopped worked on the bot a few months ago, as I've stopped watching a specific streamer as much, which was the primary channel for the bot, and instead have started streaming again myself.

The code for my bot can be found at https://github.com/elenawinters/Elenabot
The code that did the auto-connecting can be found here (commented out):  https://github.com/elenawinters/Elenabot/blob/master/bot.py#L45

For debugging, the connection flow was
1. Fetch all channels currently live on https://hasroot.com/ using a web scrapping technique. (code for this is not on github and is lost due to hard disk failure)
2. Connect to all of them.
3. Connect to all chat rooms of chatters in every chat.

This only ran when in a debug environment.

I have no intentions of working on the bot anymore at scale, as I have a database of all of the IRC messages that occurred when in debug mode and can test against the database instead of active chatrooms whenever I feel like picking up the project again.

I completely understand if you wish to keep me on the botlist.
Apologies if this is the wrong format to file for this.

### Version

user

### What system are you seeing the bot on?

Botlist

### CODE

- [X] i am human

**Comment by arrowgent** [comment]
thanks for your review.  i do remember seeing your bot in chat

```
Twitch Username | Last Seen In x Live Channels | Last Seen At
elenaberry | 255 | Fri, 09 Dec 2022 11:46:16 GMT
```


and yes indeed this is exactly why you are on these lists:
**connect to hundreds of channels to gather chat data**

we dont want you collecting chat data
dont collect what we say, who is in chat, which other chat rooms we are in, and do not aggregate that data into your database
simple as that.  dont do it.


i was trying to find the date the commit was posted with your username
seems github cant search the commits as easily as before...

enjoy your ban
