### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by errorgtb** [arrowgent/Twitchtv-Bots-List#21]
Hey there, I was trying to open my channel and ended up typing it into google and I saw this repo popup, apparantly my channel had been added here? 

I'm about 99.99% sure I am in fact human. hopefully i don't find out the opposite lol.
[channel](https://www.twitch.tv/errorgtb)

Thanks in advance, Error.

**Comment by arrowgent** [comment]
```
Twitch Username | Last Seen In x Live Channels | Last Seen At
errorgtb | 421 | Sat, 12 Nov 2022 13:01:35 GMT

```


interesting...
ill remove you now but if it shows up again youre on the list.
