### ISSUE TITLE
Removal request for "nightmarejoker2"

### ISSUE THREAD

**Issue by dori4n** [arrowgent/Twitchtv-Bots-List#24]
Hello,

The user [NightmareJoker2](https://www.twitch.tv/nightmarejoker2) is not a bot.
Please remove the username from the list following the instructions at https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository
While it is regularly present in ~600 channels, the user usually has the channel open and is watching.
In fact, you'd do good to put that username on a list of users of known safe users to unban, unrestrict, and unmark as suspicious instead.

I would also strongly urge you to leave the *other bots* alone.

Thank you.

**Comment by Ravendwyr** [comment]
I can vouch for NightmareJoker2 as well. They are an active chatter in a stream I moderate for.

**Comment by arrowgent** [comment]
user is not present on history at: 
https://twitchinsights.net/bots
which is the normal place that automation would have put them on my list

however they were somehow on my list, i dont know.  searching commits with the new UI here is not as easy as it used to be, indiciated when they were added...


also,
`https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository`
has nothing to do with how this is operated



lastly, telling me how to manage my repo by telling me to *leave other bots alone* is not a good suggestion.
tell these bots not to visit my chat and collect my user data.

**Comment by dori4n** [comment]
> also,
> 
> `https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository`
> 
> has nothing to do with how this is operated
> 

The link describes how to remove something from the commit history. This is what you should do.
 
> 
> lastly, telling me how to manage my repo by telling me to *leave other bots alone* is not a good suggestion.
> 
> tell these bots not to visit my chat and collect my user data.

You are aware that people who want to collect your *public* user data can do so without announcing themselves, right? Banning them also doesn't stop them. You will more than likely get a real user banned who just has many channels open and not do anything of value. 
Also, many of the bots on the *good bot* list do collect your user data, too. And they keep it indefinitely. So does Twitch since at least 2017. Do try the data export function.
