### ISSUE TITLE
move kofistreambot to goodbots

### ISSUE THREAD

**Issue by deadYokai** [arrowgent/Twitchtv-Bots-List#26]
`kofistreambot` used to integrate Ko-fi into twitch chat

[https://help.ko-fi.com/hc/en-us/articles/4411251874193-Connect-Ko-fi-to-Twitch-for-Payment-Alerts](https://help.ko-fi.com/hc/en-us/articles/4411251874193-Connect-Ko-fi-to-Twitch-for-Payment-Alerts)

**Comment by arrowgent** [comment]
thanks.


https://github.com/arrowgent/Twitchtv-Bots-List/commit/c557c9708edc02ff98e38601498eb4b7a0b85f6d
