### ISSUE TITLE
SoundofRaindrops not a bot

### ISSUE THREAD

**Issue by Veatra** [arrowgent/Twitchtv-Bots-List#27]
> Hello. I came from the ** raid. I have been banned from random streams since I have been put on a bot list. I am not a bot. I have had this account since 2015 and is not a new one. Unfortunately for me even after I explained that to a few mods the appeal has been rejected but I guess I can't do much about that.

**Comment by arrowgent** [comment]
might have been your use of the channel points miner

https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

however i dont see your name on the twitchinsights

https://twitchinsights.net/bots

so...ill remove you from the list.
good luck
