### ISSUE TITLE
opontifex (Twitch streamer)

### ISSUE THREAD

**Issue by oPontifeX** [arrowgent/Twitchtv-Bots-List#28]
I've been a streamer for 3 years, I'm not a bot. It's incredible how easy this is to verify and how they replicate this false information.

**Comment by arrowgent** [comment]
yes you can stream and still abuse the IRC chat system.


https://twitchinsights.net/bots
Twitch Username	Last Seen In x Live Channels	Last Seen At
opontifex	151	Fri, 26 Jan 2024 22:48:57 GMT


you get on the list automatically when your username is seen in over 150 channels within 24 hours
its a fairly hard thing to do as a "normal" user of the website.  think about it
you must have used something which put your username in those channels

**Comment by oPontifeX** [comment]
Yes, I have many friends, I visit and am a sub in several. I'm a very good bot then

**Comment by arrowgent** [comment]
right.  ill remove you but if you end up back on the list then consider not using the software which is in so many channels simultaneously...

https://github.com/arrowgent/Twitchtv-Bots-List/commit/1a92c86dc5254934e4a724964008d312a14de0df

**Comment by oPontifeX** [comment]
thank you very much!
