### ISSUE TITLE
My account is falsly listed as a bot

### ISSUE THREAD

**Issue by 8e3** [arrowgent/Twitchtv-Bots-List#30]
Hi, my twitch account arctlco is listed as a bot, this may be because my account was hacked a few months ago.
Please remove it from your list, as I've been falsly banned from a ton of channels...

**Comment by arrowgent** [comment]
`cat list.txt |grep arctlco`

i dont see your name.  perhaps did you change your name?
if your changed your name it got removed

...but if you got hacked

```
arctlco	1,675	Fri, 18 Aug 2023 02:01:24 GMT
```
1675 channels in august 2023 is a lot...
