### ISSUE TITLE
I'm not a bot

### ISSUE THREAD

**Issue by oozebro** [arrowgent/Twitchtv-Bots-List#9]
I was listed on this list (oozebrood) however I'm not a bot. Please update.

**Comment by arrowgent** [comment]
hmmm.... you were seen in 166 different channels within 24 hours

ok sure

Twitch Username | Last Seen In x Live Channels | Last Seen At
-- | -- | --
oozebrood | 166 | Fri, 11 Mar 2022 02:02:27 GMT



oozebrood
{
  "data": [
    {
      "id": "254169644",
      "login": "oozebrood",
      "display_name": "oozebrood",
      "type": "",
      "broadcaster_type": "affiliate",
      "description": "Variety outdoor IRL streamer who's passion in live is fish sandwiches. Come along for the adventure and see what we find next!",
      "profile_image_url": "",
      "offline_image_url": "offline_image-1920x1080.png",
      "view_count": 119119,
      "created_at": "2018-09-02T01:20:17Z"
    }
  ]
}



checked your clips and highlights

sorry, i do a lot of automated based on this list:
https://twitchinsights.net/bots
